default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: ubuntu
  password: Lucasdfg07


development:
  <<: *default
  database: ElephantRH_development

test:
  <<: *default
  database: ElephantRH_test

production:
  <<: *default
  database: ElephantRH_production
  username: ElephantRH
  password: <%= ENV['ELEPHANTRH_DATABASE_PASSWORD'] %>
